//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.01.22 at 11:30:52 PM MSK 
//


package com.abndev.asan.gkb.person.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.abndev.asan.gkb.person.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetPerson_QNAME = new QName("http://data.gbd.chdb.scb.kz/", "getPerson");
    private final static QName _GetPersonResponse_QNAME = new QName("http://data.gbd.chdb.scb.kz/", "getPersonResponse");
    private final static QName _IOException_QNAME = new QName("http://data.gbd.chdb.scb.kz/", "IOException");
    private final static QName _JAXBException_QNAME = new QName("http://data.gbd.chdb.scb.kz/", "JAXBException");
    private final static QName _ScbException_QNAME = new QName("http://data.gbd.chdb.scb.kz/", "ScbException");
    private final static QName _SOAPException_QNAME = new QName("http://data.gbd.chdb.scb.kz/", "SOAPException");
    private final static QName _SendMessageFault1SendMessageFault_QNAME = new QName("http://bip.bee.kz/SyncChannel/v10/Types", "SendMessageFault1_SendMessageFault");
    private final static QName _UserId_QNAME = new QName("http://bip.bee.kz/SyncChannel/v10/Types", "userId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.abndev.asan.gkb.person.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetPersonResponse }
     * 
     */
    public GetPersonResponse createGetPersonResponse() {
        return new GetPersonResponse();
    }

    /**
     * Create an instance of {@link PersonDetailsRequest }
     * 
     */
    public PersonDetailsRequest createPersonDetailsRequest() {
        return new PersonDetailsRequest();
    }

    /**
     * Create an instance of {@link PersonDetailsResponse }
     * 
     */
    public PersonDetailsResponse createPersonDetailsResponse() {
        return new PersonDetailsResponse();
    }

    /**
     * Create an instance of {@link SyncSendMessageResponse }
     * 
     */
    public SyncSendMessageResponse createSyncSendMessageResponse() {
        return new SyncSendMessageResponse();
    }

    /**
     * Create an instance of {@link GbdBillingResponse }
     * 
     */
    public GbdBillingResponse createGbdBillingResponse() {
        return new GbdBillingResponse();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link GetPerson }
     * 
     */
    public GetPerson createGetPerson() {
        return new GetPerson();
    }

    /**
     * Create an instance of {@link IOException }
     * 
     */
    public IOException createIOException() {
        return new IOException();
    }

    /**
     * Create an instance of {@link JAXBException }
     * 
     */
    public JAXBException createJAXBException() {
        return new JAXBException();
    }

    /**
     * Create an instance of {@link ScbServiceFault }
     * 
     */
    public ScbServiceFault createScbServiceFault() {
        return new ScbServiceFault();
    }

    /**
     * Create an instance of {@link SOAPException }
     * 
     */
    public SOAPException createSOAPException() {
        return new SOAPException();
    }

    /**
     * Create an instance of {@link StatusInfo }
     * 
     */
    public StatusInfo createStatusInfo() {
        return new StatusInfo();
    }

    /**
     * Create an instance of {@link ErrorInfo }
     * 
     */
    public ErrorInfo createErrorInfo() {
        return new ErrorInfo();
    }

    /**
     * Create an instance of {@link SenderInfo }
     * 
     */
    public SenderInfo createSenderInfo() {
        return new SenderInfo();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link ResponseData }
     * 
     */
    public ResponseData createResponseData() {
        return new ResponseData();
    }

    /**
     * Create an instance of {@link SyncSendMessageRequest }
     * 
     */
    public SyncSendMessageRequest createSyncSendMessageRequest() {
        return new SyncSendMessageRequest();
    }

    /**
     * Create an instance of {@link RequestData }
     * 
     */
    public RequestData createRequestData() {
        return new RequestData();
    }

    /**
     * Create an instance of {@link SendMessage }
     * 
     */
    public SendMessage createSendMessage() {
        return new SendMessage();
    }

    /**
     * Create an instance of {@link SendMessageResponse }
     * 
     */
    public SendMessageResponse createSendMessageResponse() {
        return new SendMessageResponse();
    }

    /**
     * Create an instance of {@link UserIdSoapHeaders }
     * 
     */
    public UserIdSoapHeaders createUserIdSoapHeaders() {
        return new UserIdSoapHeaders();
    }

    /**
     * Create an instance of {@link SyncMessageInfoResponse }
     * 
     */
    public SyncMessageInfoResponse createSyncMessageInfoResponse() {
        return new SyncMessageInfoResponse();
    }

    /**
     * Create an instance of {@link SyncMessageInfo }
     * 
     */
    public SyncMessageInfo createSyncMessageInfo() {
        return new SyncMessageInfo();
    }

    /**
     * Create an instance of {@link GetPersonResponse.Return }
     * 
     */
    public GetPersonResponse.Return createGetPersonResponseReturn() {
        return new GetPersonResponse.Return();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPerson }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPerson }{@code >}
     */
    @XmlElementDecl(namespace = "http://data.gbd.chdb.scb.kz/", name = "getPerson")
    public JAXBElement<GetPerson> createGetPerson(GetPerson value) {
        return new JAXBElement<GetPerson>(_GetPerson_QNAME, GetPerson.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPersonResponse }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link GetPersonResponse }{@code >}
     */
    @XmlElementDecl(namespace = "http://data.gbd.chdb.scb.kz/", name = "getPersonResponse")
    public JAXBElement<GetPersonResponse> createGetPersonResponse(GetPersonResponse value) {
        return new JAXBElement<GetPersonResponse>(_GetPersonResponse_QNAME, GetPersonResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IOException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link IOException }{@code >}
     */
    @XmlElementDecl(namespace = "http://data.gbd.chdb.scb.kz/", name = "IOException")
    public JAXBElement<IOException> createIOException(IOException value) {
        return new JAXBElement<IOException>(_IOException_QNAME, IOException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link JAXBException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link JAXBException }{@code >}
     */
    @XmlElementDecl(namespace = "http://data.gbd.chdb.scb.kz/", name = "JAXBException")
    public JAXBElement<JAXBException> createJAXBException(JAXBException value) {
        return new JAXBElement<JAXBException>(_JAXBException_QNAME, JAXBException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ScbServiceFault }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ScbServiceFault }{@code >}
     */
    @XmlElementDecl(namespace = "http://data.gbd.chdb.scb.kz/", name = "ScbException")
    public JAXBElement<ScbServiceFault> createScbException(ScbServiceFault value) {
        return new JAXBElement<ScbServiceFault>(_ScbException_QNAME, ScbServiceFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SOAPException }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SOAPException }{@code >}
     */
    @XmlElementDecl(namespace = "http://data.gbd.chdb.scb.kz/", name = "SOAPException")
    public JAXBElement<SOAPException> createSOAPException(SOAPException value) {
        return new JAXBElement<SOAPException>(_SOAPException_QNAME, SOAPException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ErrorInfo }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ErrorInfo }{@code >}
     */
    @XmlElementDecl(namespace = "http://bip.bee.kz/SyncChannel/v10/Types", name = "SendMessageFault1_SendMessageFault")
    public JAXBElement<ErrorInfo> createSendMessageFault1SendMessageFault(ErrorInfo value) {
        return new JAXBElement<ErrorInfo>(_SendMessageFault1SendMessageFault_QNAME, ErrorInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserIdSoapHeaders }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link UserIdSoapHeaders }{@code >}
     */
    @XmlElementDecl(namespace = "http://bip.bee.kz/SyncChannel/v10/Types", name = "userId")
    public JAXBElement<UserIdSoapHeaders> createUserId(UserIdSoapHeaders value) {
        return new JAXBElement<UserIdSoapHeaders>(_UserId_QNAME, UserIdSoapHeaders.class, null, value);
    }

}
